dash_within_django/urls.py
from django.urls import path, re_path
from . import views

from . import dash_app_base_generic # this loads the Dash app
from . import dash_layouts
from .dash_server import app, server


app_name = 'dash_within_django'

urlpatterns = [
                re_path('^_dash-', views.dash_ajax),

                path('home/', views.index, name='index'),
                path('skills/', views.skills, name='skills'),
                path('experience/', views.experience, name='experience'),
                path('education/', views.education, name='education'),
                path('ambitions/', views.ambitions, name='ambitions'),


                path('dashboard_example/', views.dashboard_example1, name='dashboard_example1'),
                path('dashboard_example2/', views.dashboard_example2, name='dashboard_example2'),

              ]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #admin
    path('admin/', admin.site.urls),

    # app:
    path('', include('dash_within_django.urls')),

    # end of urls list. append static doc folder:
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dash_within_django/models.py
from django.db import models

class Author(models.Model):

    name = models.CharField(max_length=100)

dash_within_django/views.py
# Django related imports:
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Author

# Dash related imports:
from .dash_server import dash_dispatcher, clean_dash_content
from django.views.decorators.csrf import csrf_exempt


def index(request):
    print("Function: index()")
    return render(request, 'dash_within_django/index.html')

def skills(request):
    return render(request, 'dash_within_django/skills.html')

def experience(request):
    return render(request, 'dash_within_django/experience.html')

def education(request):
    return render(request, 'dash_within_django/education.html')

def ambitions(request):
    return render(request, 'dash_within_django/ambitions.html')

@csrf_exempt
def dash_ajax(request, **kwargs):
    print('Function: dash_ajax')
    return HttpResponse(dash_dispatcher(request,), content_type='application/json')

def dashboard_example1(request):

    # get the django context:
    # author = get_object_or_404(Author, pk=author_id)

    print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()
    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    print(dash_content)

    context = {'dash_content': dash_content}

    return render(request, 'dash_within_django/dashboard_example1.html', context=context)


def dashboard_example2(request):

    print("Function: dash_django_page2(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()
    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    print(dash_content)

    context = {'dash_content': dash_content}

    return render(request, 'dash_within_django/dashboard_example2.html', context=context)

dash_within_django/templates/dash_within_django/ambitions.html
{% extends "dash_within_django/base_app_site.html" %}
{% load static %}
{% block content %}

<style type="text/css">

.bg-img {
      background: url("{% static 'dash_within_django/images/background2.jpg' %}") no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      height:2000px;
      /* position:absolute; */
      width:100vw;
      overflow-x: hidden;
      /* margin-left:-20px; */
      margin-top:-10px;
      /* left:0
      top:0; */
    }
.right_col{
    overflow-x: hidden;
}
    .nav_menu{
        margin-bottom:0;
    }

.nav-md .container.body .right_col{
    padding-left:0;
}

.bg-img h1, .bg-img h2{
    color:black;
}

.inner{
padding:50px;

}

li, a, p {color: black;}

.primary-text{
    width:900px;
    font-size:17px;
             }

.title-divider{
    width: 80px;
    height: 5px;
    background-color: #1aba9a;
    margin: 10px 0 25px;
}

.about-con ul{
    list-style: none;
    margin: 0;
    padding: 0;
}

.about-con ul li:first-child {
    padding: 0 0 12px;
}

.about-con ul li {
    padding: 12px 0;
}

.container-sub {
    width: 100%;
    margin: 0 auto;
    padding-top: 25px;
    padding-bottom: 25px;
}

.container-sub, h1 {
    position: relative;
}

h2 {
    font-size: 20px;
    margin-top: 10px;
}

.button, .inner h1, .inner h2, .inner h3, .inner h4, .inner h5 {
    color: #2a2b39;
    /* text-transform: uppercase; */
    font-family: Oswald,sans-serif;
}

/* body, h1, h2, h3, h4, h5 {
    font-weight: 400;
} */

.margin-top10 {
    margin-top: 10px;
}

.col-4 {
    width: 33.33333333%;
}

.skill-list ul li {
    padding: 5px 0 0;
    list-style: none;
    font-size:17px;
}


.left-col, .right-col {
    float: left;
    margin-top:10px;
}

.list {
    font-size: 15px;
    color:black;
    margin-left:0;
    padding-top:30px;
}

.>td{
    margin-bottom:20px;
}

tr.list-item>td{
  padding-bottom: 1em;
}

.list-text {
    padding-left:15px;
}

</style>


<div class="right_col" role="main">
    <div class='bg-img'>
        <div class="inner">
            <h1>Ambitions</h1>

            <div class='title-divider'></div>
              <div class="container-sub skill-list">
                  <div class="row">
                      <h2>Key Ambitions</h2>
                      <div class="col-4 margin-top10" style='display:inline;'>
                          <p class='primary-text'>
                              Below is a list of ambitions that I have in order to deliver maximum
                              business value through data and technologies:
                          </p>
                          <div  style='margin-top:20px;'>
                          <div class='left-col'>
                              <table class='list'>
                                  <tr class='list-item'>
                                      <td><i class='fa fa-exchange'></i></td>
                                      <td class='list-text'>Build Interconnected Systems</td>
                                  </tr>
                                  <tr class='list-item'>
                                      <td><i  class='fa fa-search'></i></td>
                                      <td class='list-text'>Produce Advanced Analytical Programs</td>
                                  </tr>
                                  <tr>

                                      <td><i class='fa fa-code-fork'></i></td>
                                      <td class='list-text'>Use Artificial Intelligence (AI) as part <br>of Integrated Processes</td>
                                </table>
                          </div>
                          <div class='right-col' style='padding-left:60px;'>
                              <table class='list'>
                                  <tr class='list-item'>
                                      <td><i class='fa fa-cogs'></i></td>
                                      <td class='list-text'>Automation of Business Processes</td>

                                  </tr>
                                  <tr class='list-item'>
                                      <td><i  class='fa fa-bar-chart'></i></td>
                                      <td class='list-text'>Deliver Key Insights On Demand</td>
                                  </tr>
                                  <tr>
                                      <td><i  class='fa fa-database'></i></td>
                                      <td class='list-text'>Develop a Global Knowledge Database of Technology <br> Solutions for Collaboration Purposes</td>
                                </table>

                          </div>
                      </div>
                      </div>
                  </div>
              </div>
         <div class="container-sub" style='padding-top:10px;'>
            <h2>Combining my Ambitions for effective business intelligence</h2>
            <p class='primary-text'>

                <!-- INCLUDE EXAMPLES OF DATA SCIENCE SOLUTION THAT SOLVED A BUSINESS problem -->

                <!-- INCLUDE EXAMPLE OF PYTHON BASED DASHBOARD SOLUTION TO SOLVE A PROBLEM -->

                I believe that the solutions required in order to deliver maximum business value through data and technology lies in the use of smart, end-to-end systems with an end goal of allowing key insights to be delivered to business leaders in an on-demand way.
                <br><br>
                Over the course of my career, the business solutions that I have delivered in order to solve data related problems in the oil and gas industry, the renewables industry and financial services industry have had a much more pronounced effect when flexbility over technologies has been permitted in conjunction with high quality datasets delivered through connected systems. I found this to be applicable whether the solution involves process automation, linear programming or more sophisticated algorithms involving machine learning. I have also experienced first hand how collaboration creates more effective solutions. Since minimising the diversity of different technologies in a project helps faciliate collaboration, I found technologies such as Python to be critical in my projects for sustainable, collaborative efforts due to its user-friendly syntax and powerful set of packages in order to solve general purpose tasks as well as advanced tasks involving machine learning, the latter which particularly excites me.
                <br><br>
                I consider myself an expert in technologies such as Alteryx and Tableau, yet my experience suggests these only work for specific use cases and generally lack the sophistication and business value required to address many business problems, which is in contrast to the solutions that I offer.
                Before I arrived at my current team, the value of Python was not apparent, nor was it used, yet it is now our core technology and I have had a leading part in demonstrating the flexibility and effectiveness of Python in delivering end-to-end analytics to meet our specific business problems.
                <br><br>
                My ambition is to help demonstrate and deliver effective solutions to clients using the visions I have listed above. This would preferably include only the use of open-sourced technologies, where applicable, combined with novel data science techniques. The prospect of achieving this excites me.
                <br>
                <br>

                </p>
        </div>



    </div>

    </div>

</div>


{% endblock %}

dash_within_django/templates/dash_within_django/base_app_site.html
<!DOCTYPE html>
<html lang="en">

    <head>

      {% block title %}<title>Edward Burmicz</title>{% endblock %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      {% load static %}



      {% block vendor_stylesheets %}
        <!-- Bootstrap -->
        <link href="{% static 'dash_within_django/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'dash_within_django/css/font-awesome.min.css' %}" rel="stylesheet">

        <!-- NProgress -->
        <link href="{% static 'dash_within_django/css/nprogress.css' %}" rel="stylesheet' %}">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static 'dash_within_django/css/daterangepicker.css' %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static 'dash_within_django/css/icheck_green.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static 'dash_within_django/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{% static 'dash_within_django/css/jqvmap.min.css' %}" rel="stylesheet"/>
      {% endblock vendor_stylesheets %}

      {% block Dash_css %}
      <!-- Add Dash css in static file -->
      <link href="{% static 'dash_within_django/css/Dash_css/react-select@1.0.0-rc.3.min.css' %}" rel="stylesheet">
      <link href="{% static 'dash_within_django/css/Dash_css/custom_dash_styles.css' %}" rel="stylesheet">
      {% endblock Dash_css %}

      {% block custom_css %}
      <!-- Custom Theme Style -->
      <link href="{% static 'dash_within_django/css/custom.css' %}" rel="stylesheet">
      {% endblock custom_css %}

    </head>

<body class="{% block body_class %}nav-md {% endblock body_class %}">
  {% block body %}
    <div class="container body">
      <div class="main_container">

        {% block sidebar %}
          <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
            {% include "dash_within_django/sidebar.html" %}
          </div>
        {% endblock sidebar %}

        {% block top_navigation %}
          <div class="top_nav">
            {% include "dash_within_django/top_navigation.html" %}
          </div>
        {% endblock top_navigation %}

        {% block content %}
          <!-- {{ content }} -->
        {% endblock content %}

      </div>
    </div>

    {% block javascripts %}

      <!-- jQuery -->
      <script src="{% static 'dash_within_django/js/jquery.min.js' %}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'dash_within_django/js/bootstrap.min.js' %}"></script>

      <!-- FastClick -->
      <script src="{% static 'dash_within_django/js/fastclick.js' %}"></script>
      <!-- NProgress -->
      <script src="{% static 'dash_within_django/js/nprogress.js' %}"></script>
      <!-- bootstrap-progressbar -->
      <script src="{% static 'dash_within_django/js/bootstrap-progressbar.min.js' %}"></script>
      <!-- iCheck -->
      <script src="{% static 'dash_within_django/js/icheck.min.js' %}"></script>
      <!-- bootstrap-daterangepicker -->
      <script src="{% static 'dash_within_django/js/moment.min.js' %}"></script>
      <script src="{% static 'dash_within_django/js/daterangepicker.js' %}"></script>
      <!-- bootstrap-wysiwyg -->
      <script src="{% static 'dash_within_django/js/bootstrap-wysiwyg.min.js' %}"></script>
      <script src="{% static 'dash_within_django/js/jquery.hotkeys.js' %}"></script>
      <script src="{% static 'dash_within_django/js/prettify.js' %}"></script>
      <!-- jQuery Tags Input -->
      <script src="{% static 'dash_within_django/js/jquery.tagsinput.js' %}"></script>
      <!-- Switchery -->
      <script src="{% static 'dash_within_django/js/switchery.min.js' %}"></script>
      <!-- Select2 -->
      <script src="{% static 'dash_within_django/js/select2.full.min.js' %}"></script>
      <!-- Parsley -->
      <script src="{% static 'dash_within_django/js/parsley.min.js' %}"></script>
      <!-- Autosize -->
      <script src="{% static 'dash_within_django/js/autosize.min.js' %}"></script>
      <!-- jQuery autocomplete -->
      <script src="{% static 'dash_within_django/js/jquery.autocomplete.min.js' %}"></script>
      <!-- starrr -->
      <script src="{% static 'dash_within_django/js/starrr.js' %}"></script>
    {% endblock %}

    <!-- Custom Theme Scripts -->
    <script src="{% static 'dash_within_django/js/custom.js' %}"></script>

  {% endblock body %}
</body>

</html>

dash_within_django/templates/dash_within_django/dashboard_example1.html
{% extends "dash_within_django/base_app_site.html" %}

{% block vendor_stylesheets %}
  {{ block.super }}
{% endblock vendor_stylesheets %}

{% block Dash_css %}
    {{ block.super}}
{% endblock Dash_css %}


{% block content %}

<div class="right_col" role="main">
    <div class="inner" style='padding-left:20px;'>
        <h1>Trading Anomaly Tracker</h1>
          <div class="title-divider"></div>
            <div class="experience-con">

                <div class='container'>
                    <div class='jumbotron' style='background-color:#d9edff; padding:35px;'>
                        <p style='font-size:16px'>
                            <b>Description:</b> The visualizations below were produced in conjunction with my MSc thesis, which involved working
                            with a major financial institution in order to find a viable method of using technology to automatically identify
                            indications of rogue trading in big data.
                             This mainly involved exploring machine learning technologies using small subsets of a database in order to
                             test whether normal trader behaviour could be learned.
                             One of the methods explored, which invovled using Decision Tree based learners, such as a Random Forest learner or the
                             xGBoost learner gave promising indications of being a viable technology for the financial investigative team to utilize.
                             This dashboard below is a modfied version of the framework used to present the results to the client.
                             The data has been faked to for client confidentiality.
                        </p>
                    </div>
                </div>

              <div class="container-sub">
                  <div class="row">

                  <div>
                  </div>

                      <div>


                        {{ dash_content | safe }}

                     </div>
               </div>
           </div>



       </div>
    </div>
</div>





{% endblock %}


{% block javascripts %}
  {{ block.super}}

{% endblock javascripts %}

dash_within_django/templates/dash_within_django/dashboard_example2.html
{% extends "dash_within_django/base_app_site.html" %}

{% block vendor_stylesheets %}
  {{ block.super }}
{% endblock vendor_stylesheets %}

{% block Dash_css %}
    {{ block.super}}
{% endblock Dash_css %}


{% block content %}

<div class="right_col" role="main">
    <div class="inner" style='padding-left:20px;'>
        <h1>Magnetic Anomaly Detector Results</h1>
          <div class="title-divider"></div>
            <div class="experience-con">

                <div class='container'>
                    <div class='jumbotron' style='background-color:#d9edff; padding:35px;'>
                        <p style='font-size:16px'>
                            <b>Description:</b> The visualizations below are the results of a novel supervised machine learning prototype
                            that I coded and applied to magnetic survey data, which is typically used in oil and gas surveys to idenfify
                            installation operation risks.
                            My motivation in building this was to further learn about machine learning in a business context as well as assist
                            in the consistent and reliable identification of magnetic anomalies.
                            As can be seen from the dashboard below, the prototype worked as the machien was correctly able to identify anoamlies from new data.
                        </p>
                    </div>
                </div>

              <div class="container-sub">
                  <div class="row">

                  <div>
                  </div>

                      <div>


                        {{ dash_content | safe }}

                     </div>
               </div>
           </div>



       </div>
    </div>
</div>





{% endblock %}


{% block javascripts %}
  {{ block.super}}

{% endblock javascripts %}

dash_within_django/templates/dash_within_django/education.html
{% extends "dash_within_django/base_app_site.html" %}
{% load static %}
{% block content %}

<style type="text/css">

.bg-img {
      background: url("{% static 'dash_within_django/images/background2.jpg' %}") no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      height:2000px;
      /* position:absolute; */
      width:100vw;
      overflow-x: hidden;
      /* margin-left:-20px; */
      margin-top:-10px;
      /* left:0
      top:0; */
    }
.right_col{
    overflow-x: hidden;
}
    .nav_menu{
        margin-bottom:0;
    }

.nav-md .container.body .right_col{
    padding-left:0;
}

.bg-img h1, .bg-img h2{
    color:black;
}

.inner{
padding:50px;

}

li, a, p {color: black;}



.about-con ul{
    list-style: none;
    margin: 0;
    padding: 0;
}

.about-con ul li:first-child {
    padding: 0 0 12px;
}

.about-con ul li {
    padding: 12px 0;
}

.container-sub {
    width: 100%;
    margin: 0 auto;
    padding-top: 25px;
    padding-bottom: 25px;
}

.container-sub, h1 {
    position: relative;
}

h2 {
    font-size: 20px;
    margin-top: 10px;
}

.button, .inner h1, .inner h2, .inner h3, .inner h4, .inner h5 {
    color: #2a2b39;
    text-transform: uppercase;
    font-family: Oswald,sans-serif;
}


.margin-top10 {
    margin-top: 10px;
}

.col-4 {
    width: 33.33333333%;
}

.skill-list ul {
    margin: 0;
    padding: 0;
}

.skill-list ul li {
    padding: 5px 0 0;
    list-style: none;
    font-size:17px;
}

.skill-list ul {
    -moz-column-count: 3;
    -moz-column-gap: 20px;
    -webkit-column-count: 3;
    -webkit-column-gap: 20px;
    column-count: 3;
    column-gap: 20px;
    width:500px;
}

.skill-list ul li:before {
    content: "\f00c";
    font-family: FontAwesome;
    font-size: 15px;
    margin: 0 5px 0 0;
}

.education-details, .experience-details {
    float: left;
}

.margin-top50 {
    margin-top: 50px;
}
.flot-left {
    float: left;
}

.experience-con h5 {
    margin: 5px 0 7px;
}

h5 {
    font-size: 18px;
}


.experience-con span {
    font-size: 16px;
    color: #2a2b39;
}

.margin-top50 {
    margin-top: 50px;
}

.margin-bottom50 {
    margin-bottom: 50px;
}
.col-6 {
    width: 50%;
}
.col-1, .col-10, .col-11, .col-12, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9 {
    float: left;
    position: relative;
}

h4 {
    font-size: 25px;
    font-weight: 100;
    line-height: 30px;
}


h2, h4 {
    margin: 0;
}
menu, ol, ul {
    padding: 0 0 0 40px;
}

dl, menu, ol, ul {
    margin: 1em 0;
}


.full-divider {
    width: 100%;
    height: 1px;
    background-color: black;
    margin: 50px 0 0;
}

.clear, .clearfix:after, .full-divider, .row:after {
    clear: both;
}

.experience-details{
    width:80%;
}

.company_name{
    font-size:17px;
}
.job_title{
    font-size:22px;
}
.job_dates{
    font-size:17px;
}
.job_description {
    font-size:17px;
}

.bullet_list li{
    font-size:17px;
}

</style>


<div class="right_col" role="main">
    <div class='bg-img'>
        <div class="inner">
            <h1>Education</h1>
              <div class="title-divider"></div>
                <div class="experience-con">
                  <div class="container-sub">
                      <div class="row">
                          <div class="experience-details">
                              <div class="col-6 margin-bottom50 margin-top50">
                                  <div class="flot-left">
                                      <p class='company_name'>MSc Data Science </p>
                                      <p class='job_title'>King's College London</p>
                                      <p class='job_dates'>September 2016 - September 2017</p>
                                  </div>
                              </div>
                              <div class="col-6 margin-bottom50 margin-top50 no-margin-top">
                                  <p class='job_description'>
                                    Distinction achieved. Wide ranging data science curriculum. Modules included ‘Machine Learning’, ‘Data Mining’ and ‘Big Data Technologies’. Learned advanced techniques in:
                                       <ul class='bullet_list'>
                                           <li>Python</li>
                                           <li>R</li>
                                           <li>SQL and NoSQL technologies</li>
                                           <li>Spark with PySpark</li>
                                           <li>Tableau</li>
                                       </ul>
                                   </p>


                              </div>
                          </div>
                          <div class="full-divider"></div>
                          <div class="experience-details">
                              <div class="col-6 margin-bottom50 margin-top50">
                                  <div class="flot-left">
                                      <p class='company_name'>BSc Geophyiscs</p>
                                      <p class='job_title'>University of East Anglia</p>
                                      <p class='job_dates'>September 2007 - August 2011</p>
                                  </div>
                              </div>
                              <div class="col-6 margin-bottom50 margin-top50 no-margin-top">
                                  <p class='job_description'>
                                      2-1 achieved.<br><br>
                                      A variety of mathematical and technical modules studied. The year in industry was taken place at Gardline Geosurvey.
                                   </p>


                              </div>
                          </div>

                       </div>
                   </div>
               </div>
           </div>

{% endblock %}

dash_within_django/templates/dash_within_django/sidebar.html
{% load static %}

<style>

.logo {text-transform: lowercase; }

.logo i {
        background: url("{% static 'dash_within_django/images/artificial-intelligence.svg' %}") no-repeat 0 0;
        background-size: 5rem;
        float: left;
        height: 5.2rem;
        text-indent: -4000px;
        /*If you remove text-indent and add: */
        /*padding-left: 6rem;*/
        vertical-align: middle;
        width: 4.8rem;
        padding-left:10px;
        }
</style>

<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a class="site_title"><p style='padding-left:10px;' class="logo"><i></i></p>
        <div style='text-align:center; margin-top:60px;'><span style='font-size:23px;'>Edward Burmicz</span></div>
        <div style='text-align:center;'><span style='font-size:13.5px;'> Full Stack Data Scientist</span></div>
    </a>


  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
   <div style='text-align:center;'>
     <div class="profile_pic" style='width:100%'>
      <!-- <img style='margin-left:0;' src="{% static 'dash_within_django/images/avatar.png' %}" class="img-circle profile_img"> -->
      <img style='margin-left:0; margin-top:30px; width:30%' src="{% static 'dash_within_django/images/avatar.png' %}" class="img profile_img">
     </div>
   </div>
    <div class="profile_info" style='width:100%; text-align:center'>
      <span>Contact Address:</span>
      <h2>eburmicz@gmail.com</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />
  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu toggled">
    <div class="menu_section toggled">
      <h3>Navigation</h3>
      <ul class="nav side-menu">
        <li><a href="{% url 'dash_within_django:index' %}"><i class="fa fa-home"></i> About Me</a>
        </li>
        <li><a><i class="fa fa-edit"></i> Curriculum Vitae<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{% url 'dash_within_django:skills' %}"> Skills</a></li>
          <li><a href="{% url 'dash_within_django:experience' %}"> Experience</a></li>
          <li><a href="{% url 'dash_within_django:education' %}"> Education</a></li>
        </ul>
        <li><a><i class="fa fa-bar-chart-o"></i> Example Work<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'dash_within_django:dashboard_example1' %}"> Dashboard: Rogue Detection Visualization</a></li>
          </ul>
        </li>
        <li><a href="{% url 'dash_within_django:ambitions' %}"><i class="fa fa-comment"></i> Ambitions</a>
        </li>
        <li><a><i class="fa fa-desktop"></i> Additional Resources<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="https://www.linkedin.com/in/edward-burmicz-900058146/">Linkedin</a></li>
            <li><a href="download.html">Download CV<span class="label label-success pull-right">Coming Soon</span></a></li>
          </ul>
        </li>

      </ul>
    </div>

  </div>
  <!-- /sidebar menu -->

</div>

dash_within_django/templates/dash_within_django/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">

        <li role="presentation" class="dropdown" style='margin-right:20px; margin-left:5px;'>
            <p style='display:inline-block'>Send E-mail:</p>
          <a style='display:inline-block' href='mailto:eburmicz@gmail.com' class="dropdown-toggle info-number" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <!-- <span class="badge bg-green">6</span> -->
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
          </ul>
        </li>

      <li role="presentation" class="dropdown">
          <p style='display:inline-block'>My LinkedIn:</p>
        <a style='display:inline-block' href='https://www.linkedin.com/in/edward-burmicz-900058146/' class="dropdown-toggle info-number" aria-expanded="false">
          <i class="fa fa-linkedin-square"></i>
          <!-- <span class="badge bg-green">6</span> -->
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
        </ul>
      </li>


    </ul>
  </nav>
</div>